### ISSUE TITLE
Cannot join a raffle with MetaMask and Ledger account

### ISSUE THREAD

**Issue by remyroy** [poap-xyz/poap-fun#61]
More details in https://github.com/MetaMask/metamask-extension/issues/10240#issuecomment-863654605

**Comment by remyroy** [comment]
Looking at the logs on https://gist.github.com/remyroy/7baa9f06ead61c897ba884635b0a5ae6 , you can also see that poap-fun seems to be using deprecated structures or methods from MetaMask.

![console](https://user-images.githubusercontent.com/303593/122490822-d46c6780-cfb0-11eb-80b0-0d3722017272.png)

**Comment by remyroy** [comment]
Signing code seems to be in https://github.com/poap-xyz/poap-fun/blob/7dad2a84be830e54b9fd3c969bbd78b98958a21a/frontend/src/lib/hooks/useCustomState.tsx#L157

**Comment by ragonzal** [comment]
Hello @remyroy, thanks for reporting the issue. I just merged the PR #62 with the fix.

The EIP712 signature on Ledger wallets is a hot new feature (awesome!!!) and we weren't able to try it before. The response comes a little different when it's from a hardware wallet than a simple software account.
The problem was the backend verifying the signature, not the actual signature process.

Anyway, you should be able to join raffles with you HW.
Let me know if it works!

**Comment by remyroy** [comment]
Great job! Unfortunately, the raffle I wanted to join (https://poap.fun/284) is closed now. I'll try to find another one soon.

**Comment by remyroy** [comment]
I was able to join another raffle so it seems this fix is good 👍
